/* THIS FILE IS GENERATED AUTOMATICALLY
 * DO NOT EDIT THIS FILE
 */

namespace NativePlugins.Types
{
    public enum Algorithm
    {
        PolicyEvaluation,
        PolicyIteration,
        ValueIteration,
        MonteCarloExploringStarts,
        MonteCarloOnPolicyFirstVisit,
        MonteCarloOffPolicy,
        Sarsa,
        QLearning,
        ExpectedSarsa,
        DynaQ,
        EpisodicSemiGradiantSarsa,
        DeepQLearning,
        Reinforce,
        ReinforceWithBaseline,
        OneStepActorCritic,
        PpoA2cStyle,
    }
}
