[package]
name = "ffi-csharp"
version = "0.1.0"
authors = [
    "Axel Cocat <ax.cocat@gmail.com>"
]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.16"
quote = "1.0.3"
proc-macro2 = "1.0.9"
heck = "0.3.1"
regex = "1.3.4"
